### ISSUE TITLE
'iconAddSolid' was not found in 'carbon-icons'

### ISSUE THREAD

**Issue by anupamsomani1** [IBM/carbon-icons#77]
#### 1. Icon name
'iconAddSolid' was not found in 'carbon-icons'
'iconCheckmarkSolid' was not found in 'carbon-icons'

#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.
Creating new React Application include carbon-icons library  but below error its comes.

#### 4. Screen Shot
Please add the following screen shots to this issue:
<img width="699" alt="screen shot 2018-08-20 at 12 24 19 pm" src="https://user-images.githubusercontent.com/35505922/44367288-2e0c5a80-a484-11e8-8a1f-8d79a3dae67a.png">

1. Close-up screen shot of the icon with the pixel grid turned on 
2. Screen shot of the icon in context with your use case. ##

**Comment by joshblack** [comment]
Hi @anupamsomani1! 👋 Could you share the package version for `carbon-icons` that you are using? These should show up in v7 of the icons 😄

**Comment by anupamsomani1** [comment]
"carbon-addons-cloud": "^2.1.0",
    "carbon-addons-cloud-react": "1.3.0",
    "carbon-components": "9.7.1",
    "carbon-components-react": "6.20.0",
    "carbon-icons": "^6.3.2",

**Comment by joshblack** [comment]
Thanks @anupamsomani1! You are using `v6.3.2`, but those icons are available in `7.0.7`. Updating should help!

**Comment by anupamsomani1** [comment]
Yeah I tried that but still when I am using below code that Image was not rendering 
   <DetailPageHeader title="Detail Page Header">
          <Icon name="watson" />
 </DetailPageHeader>

<img width="474" alt="screen shot 2018-08-20 at 3 09 17 pm" src="https://user-images.githubusercontent.com/35505922/44369381-0a98de00-a48b-11e8-8dce-d26aa77e9cf0.png">

**Comment by asudoh** [comment]
Hi 👋 do you want to create a reduced case, based on https://codesandbox.io/s/x2mjypo6pp? Thanks!

**Comment by anupamsomani1** [comment]
Hi @asudoh  That was strange in codesandbox It's working but I am trying to integrate in our solution that the will comes up.
So here my question is there is any need to  import `carbon-icons`. I think '`carbon-components-react'` has duty to import `carbon-icons` is my understanding correct ?

**Comment by joshblack** [comment]
@anupamsomani1 `carbon-icons` is listed as a `peerDependency` on the project 👍 

https://github.com/IBM/carbon-components-react/blob/052822271c4663c153e25bd92f00ccb49e278153/package.json#L122

**Comment by asudoh** [comment]
Hi again 👋 `npm i -S carbon-icons` would be something you’d want - Hope it helps!

**Comment by asudoh** [comment]
In case this is what you are asking; `<Icon>` as of today has two ways to use - One is `<Icon icon={iconSomething}>` where `iconSomething` is a named import of `carbon-icons` (as you brought up). Another is `<Icon name="add—solid”>` but it’s deprecated.

You can see the demo of all options in http://react.carbondesignsystem.com/?selectedKind=Icon&selectedStory=Default by going to Knobs tab at the bottom and changing some props there. The source code of that demo can be found at https://github.com/IBM/carbon-components-react/blob/eb8a297/src/components/Icon/Icon-story.js. Hope it helps!

**Comment by joshblack** [comment]
Going to close this as this seems more like a usage question at this point. Feel free to reach out in the #carbon-react slack channel if you have additional questions around how the `<Icon>` component works!
