### ISSUE TITLE
Contribution: Success 

### ISSUE THREAD

**Issue by emily827** [IBM/carbon-icons#78]
Hi!

The name of this icon is "success". It's a checkmark inside of a circle. It's going to represent when an action/event is successful. The following .zip file has the svg and an image of it in use.

[success.zip](https://github.com/IBM/carbon-icons/files/2412587/success.zip)

**Comment by tw15egan** [comment]
Seems like this already exists as `icon--checkmark--outline`

http://carbondesignsystem.com/style/iconography/library

**Comment by emily827** [comment]
Hi,

Oh, alright- thanks!
