### ISSUE TITLE
Contribution: Fail Icon

### ISSUE THREAD

**Issue by emily827** [IBM/carbon-icons#79]
The name of the icon is "fail". It's going to be used when an action/event fails. The following .zip has the svg and an image of what it looks like. 
[fail.zip](https://github.com/IBM/carbon-icons/files/2412605/fail.zip)

**Comment by asudoh** [comment]
Hi @emily827 thank you for bringing this up! Does http://www.carbondesignsystem.com/assets/icons/close--outline.svg satisfy your requirement? Another info which may be worthwhile is you can use your custom icon in `carbon-components-react`'s `<Icon>` component, by using a JSON data from SVG (XML) with a [conversion](https://github.com/IBM/carbon-icons/blob/v7.0.0/gulp-tasks/shared/formatJS.js), as [`<Icon>`'s `icon` prop](https://github.com/IBM/carbon-components-react/blob/v6.32.4/src/components/Icon/Icon.js#L172-L177). Data format examples can be found at https://unpkg.com/carbon-icons@7.0.0/dist/carbon-icons.js. Thanks!

**Comment by emily827** [comment]
Hi!
Yes, that one satisfies my requirement. Sorry, I missed that one.
