### ISSUE TITLE
Broken link on main page

### ISSUE THREAD

**Issue by markdebhailis** [IBM/carbon-icons#89]
I'm getting 404 when I click this: http://carbondesignsystem.com/style/iconography/library

**Comment by joshblack** [comment]
Hi @markdebhailis! 👋 Where do you see this link in the README? If it helps, here is the updated link 😄 https://www.carbondesignsystem.com/guidelines/iconography/library

**Comment by markdebhailis** [comment]
@joshblack sorry it's not the readme, it's repo title link, see below

![screen shot 2018-10-19 at 16 12 43](https://user-images.githubusercontent.com/2254794/47227155-11c06780-d3ba-11e8-8919-cfa457a498be.png)

**Comment by joshblack** [comment]
Oh duh, thanks for the catch! Updating now. Thanks!
