### ISSUE TITLE
Links in usage doc lead to 404's

### ISSUE THREAD

**Issue by alohr51** [IBM/carbon-icons#90]
Links under Usage header in https://github.com/IBM/carbon-icons/blob/master/docs/usage.md lead me to 404's, here are some examples:

- https://github.com/carbon-design-system/carbon-icons/tree/master/dist
- https://raw.githubusercontent.com/carbon-design-system/carbon-icons/master/dist/carbon-icons.svg
- http://carbondesignsystem.com/style/iconography/library

**Comment by joshblack** [comment]
Thanks for the heads up @alohr51! Updating now 👍
